import { Inter } from "next/font/google";
import "./globals.css";
import { ApolloWrapper } from "./client/apollo-wrapper";
import { FaustProvider } from "@faustwp/experimental-app-router/ssr";
import Header from "./components/molecules/Header";
import Footer from "./components/molecules/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={"font-Archivo"}>
        <ApolloWrapper>
          <FaustProvider>
            <Header />
            {children}
            <Footer />
          </FaustProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
}
